version: "3"

silent: true

tasks:
  default:
    desc: List all tasks
    aliases:
      - list
    cmd: task --list

  install:
    desc: Install packages
    cmds:
      - task: install:react
      - task: install:mock

  code:
    desc: Open Vscode in root
    dir: ./
    cmds:
      - code .

  dev:react:
    desc: Start dev server
    dir: ./apps/react-app
    cmds:
      - bun run dev

  install:react:
    desc: Install packages
    dir: ./apps/react-app
    cmds:
      - bun install

  install:mock:
    desc: Install packages
    dir: ./mock
    cmds:
      - bun install

  codegen:react:
    desc: Using GraphQL Code Generator for react
    dir: ./apps/react-app
    cmds:
      - bunx graphql-codegen

  codegen:flutter:
    desc: Using GraphQL Code Generator for flutter
    dir: ./apps/flutter_app
    cmds:
      - dart run build_runner build

  dev:mock:
    desc: Run Apollo Server for mock
    dir: ./mock/src
    cmds:
      - bun --hot run server.ts
